version: '3.1'

services:
  dev:
    build:
      context: .
      dockerfile: .docker/dev/Dockerfile
      args:
        SSH_KEY_PRIV: ${SSH_KEY_PRIV}
        SSH_KEY_PUB: ${SSH_KEY_PUB}
        
    volumes:
      - .:/app
    env_file:
      - '.docker/dev/.env'
      - '.docker/dev/secrets.env'
    
